---
title: "STA 160 Project"
author: "Jessica Padolina"
date: "4/30/2017"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE}
setwd("/Users/Jessica/Documents/Stats Stuff/STA-160")
la_crime = read.csv("la_crime.csv")
```

CLEANING DATA
```{r}
#Subsetting the data to contain violent crimes only

la_violent = subset(la_crime, la_crime$Crime.Code.Desc %in% 
                     c("ASSAULT WITH DEADLY WEAPON ON POLICE OFFICER","ASSAULT WITH                         DEADLY WEAPON, AGGRAVATED ASSAULT", "ASSAULT", "BATTERY -                           SIMPLE ASSAULT", "BATTERY ON A FIREFIGHTER",
                       "BATTERY POLICE (SIMPLE)", "BATTERY WITH SEXUAL CONTACT",                           "BATTERY", "CRIMINAL HOMICIDE",
                       "MANSLAUGHTER, NEGLIGENT", "HOMICIDE", "ROBBERY"))

#Create pattern for Assault, Battery, and Homicide
#Robberies already correspond to one Crime.Code.Desc string, so no pattern necessary
pathA = "ASSAULT WITH DEADLY WEAPON ON POLICE OFFICER|ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT" # Assault pathway

pathB = "BATTERY - SIMPLE ASSAULT|BATTERY ON A FIREFIGHTER|BATTERY POLICE \\(SIMPLE\\)|BATTERY WITH SEXUAL CONTACT" # Battery Pathway"
  
pathH = "CRIMINAL HOMICIDE|MANSLAUGHTER, NEGLIGENT" # Homicide Pathway" 
  
# Now use gsub() to replace each pattern with standardized crimet type
la_violent$Crime.Code.Desc = gsub(pathA, "ASSAULT", la_violent$Crime.Code.Desc) # sub for Assault

la_violent$Crime.Code.Desc = gsub(pathB, "BATTERY", la_violent$Crime.Code.Desc) # sub for Battery

la_violent$Crime.Code.Desc = gsub(pathH, "HOMICIDE", la_violent$Crime.Code.Desc) # sub for Homicide

#Splitting Coordinates column
library(stringr)
latlon = str_split_fixed(la_violent$Location.1, " ", 2)
latlon[,1] = gsub("\\(", "", latlon[,1])
latlon[,1] = gsub(",", "", latlon[,1])
latlon[,2] = gsub("\\)", "", latlon[,2])

#Converting to numeric class
latlon = apply(latlon, 2, as.numeric)

#Creating Year column
Year = substr(la_violent$Date.Occurred, 7, 10)
la_violent["Year"] <- Year
```

PLOTS
```{r}
#TABLE OF COUNTS OF CRIME PER TYPE
table(la_violent$Crime.Code.Desc)

#TIME PLOT OF ALL VIOLENT CRIME OVER TIME
#Group by Month and Year and create a new column
Mon = substr(la_violent$Date.Occurred, 1,2)
Year = substr(la_violent$Date.Occurred, 7, 10)

MonYr = paste(Mon, Year, sep = "/")
la_violent["MonYr"] <- MonYr

VCount = table(la_violent$MonYr)
VCount = data.frame(VCount)

#Change column names
colnames(VCount) = c("Date", "Count")

# Change the class of the variable 
VCount$Date = as.character(VCount$Date)

# Create a function to create a new date column
# original Date varaible is month/year
# we want to change it month/1 ( day)/ year
# reason: way to aggregate the data

monthly = function(data_col) {
  split_dates = strsplit(data_col, "/") # will split the month/year
  new_dates = sapply(split_dates, function(x) { 
    new_date = paste0(x[2], "-", x[1], "-01") # this adds the new date 
    new_date # now we have our new date = month/01/year
  })
  as.Date(new_dates)
}

VCount$Date = monthly(as.character(VCount$Date)) # run the Monthly function, variable must be a character

# order the dates
VCount = VCount[order(VCount$Date), ]

# Create the Time Series plot
TimeSeriesPlot = 
  plot_ly(VCount, x = VCount$Date, y = VCount$Count, 
          type = "scatter", mode = "lines", name = "Crime Count", line = list(color = 'rgba(67,67,67,1)', width = 2)) %>%
  layout(title = "Violent Crime 2010-2017",
         xaxis = list(title = "Date"), 
         yaxis = list(title = "Count")
  )

TimeSeriesPlot

#BAR CHARTS SHOWING COUNTS PER AREA
#Subset the data by type of Violent Crime
Assault = subset(la_violent, la_violent$Crime.Code.Desc ==  "ASSAULT")
Battery = subset(la_violent, la_violent$Crime.Code.Desc ==  "BATTERY")
Homicide = subset(la_violent, la_violent$Crime.Code.Desc ==  "HOMICIDE")
Robbery = subset(la_violent, la_violent$Crime.Code.Desc ==  "ROBBERY")


# Step 1) 
#  * Table to Dataframe Function * # 

vType = function(VTypeName, dataVar1, dataVar2){
  # create table by year
  VTypeName = table(dataVar1, dataVar2)   
  
  # create dataset for the table
  VTypeName = data.frame(VTypeName)
  
  # change column names
  colnames(VTypeName) = c("Area", "Year", "Count") 
  
  ## Pivot the table 
  Pivot = spread(VTypeName, Year, Count) 
  Pivot
}


# Step 2
# Now create the pivoted data frames for each violent crime
BPivot = vType(BType, Battery$Area.Name , Battery$Year)   # Battery
APivot = vType(AType, Assault$Area.Name , Assault$Year)   # Assault
HPivot = vType(HType, Homicide$Area.Name, Homicide$Year)  # Homicide
RPivot = vType(RType, Robbery$Area.Name , Robbery$Year)   # Robbery 


#Step 3
#  * Barchart Function * # 
# The function will later be used for the 4 diff violent crimes

ChartFunc =  
  # The function will read in each pivoted df
  # input each Var1 etc represent each var per year in the df
  function(chartName, titleName, data, dataVar1, dataVar2,
           dataVar3, dataVar4, dataVar5, dataVar6,
           dataVar7, dataVar8, dataVar9) { 
    
    chartName = 
      
      # use Plot_ly functions
      plot_ly(data, x = dataVar1) %>%
      add_bars(y = dataVar2, name = "2010") %>% # allows you to continue and start new line 
      add_bars(y = dataVar3, name = "2011", visible = FALSE) %>% # add each bar for each year
      add_bars(y = dataVar4, name = "2012", visible = FALSE) %>%
      add_bars(y = dataVar5, name = "2013", visible = FALSE) %>%
      add_bars(y = dataVar6, name = "2014", visible = FALSE) %>%
      add_bars(y = dataVar7, name = "2015", visible = FALSE) %>%
      add_bars(y = dataVar8, name = "2016", visible = FALSE) %>%
      add_bars(y = dataVar9, name = "2017", visible = FALSE) %>%
  
      layout(
        # Set up the layout 
        title = titleName, 
        xaxis = list(domain = c(0.1, 1)),
        yaxis = list(title = "Frequency"),
        showlegend = FALSE,
        updatemenus = list(
          list(
            y = 0.7,
            
            # Set up the drop down button per year
            # this will allow the user to control which year to view at a time
            
            buttons = list(
              list(method = "restyle",
                   args = list("visible", list(TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE)),
                   
                   label = "2010"),
              list(method = "restyle",
                   args = list("visible", list(FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE)),
                   label = "2011"),
              list(method = "restyle",
                   args = list("visible", list(FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE)),
                   label = "2012"),
              list(method = "restyle",
                   args = list("visible", list(FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE)),
                   label = "2013"),
              list(method = "restyle",
                   args = list("visible", list(FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE)),
                   label = "2014"),
              list(method = "restyle",
                   args = list("visible", list(FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE)),
                   label = "2015"),
              list(method = "restyle",
                   args = list("visible", list(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE)),
                   label = "2016"),
              list(method = "restyle",
                   args = list("visible", list(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE)),
                   label = "2017")))
        )
      ) 
    chartName
  }

# Step 4
# Output for the barchart per Violent Crime

AssaultChart = 
  ChartFunc(AssaultChart2, "Assault, Battery, Homicide, and Robbery per Community Area",  
            APivot, APivot$Area, APivot$`2010`, APivot$`2011`,
            APivot$`2012`, APivot$`2013`, APivot$`2014`, 
            APivot$`2015`, APivot$`2016`, APivot$`2017`)

BatteryChart = 
  ChartFunc(BatteryChart2, "Assault, Battery, Homicide, and Robbery per Community Area",
            BPivot, BPivot$Area, BPivot$`2010`, BPivot$`2011`,
            BPivot$`2012`, BPivot$`2013`, BPivot$`2014`, 
            BPivot$`2015`, BPivot$`2016`, BPivot$`2017`)

HomicideChart = 
  ChartFunc(HomicideChart2, "Assault, Battery, Homicide, and Robbery per Community Area",
            HPivot, HPivot$Area, HPivot$`2010`, HPivot$`2011`,
            HPivot$`2012`, HPivot$`2013`, HPivot$`2014`, 
            HPivot$`2015`, HPivot$`2016`, HPivot$`2017`)

RobberyChart = 
  ChartFunc(RobberyChart2, "Assault, Battery, Homicide, and Robbery per Community Area",
            RPivot, RPivot$Area, RPivot$`2010`, RPivot$`2011`,
            RPivot$`2012`, RPivot$`2013`, RPivot$`2014`,
            RPivot$`2015`, RPivot$`2016`, RPivot$`2017`)

p <- subplot(AssaultChart, BatteryChart, HomicideChart, RobberyChart)
p


#TIME SERIES PLOT BROKEN DOWN BY TYPE OF CRIME
VType = table(la_violent$Crime.Code.Desc, la_violent$MonYr)
VType = data.frame(VType)

# Change the column names
colnames(VType) = c("Type", "Date", "Count")

# Change the class of the variable 
VType$Date = as.character(VType$Date)

VType$Date = monthly(as.character(VType$Date)) # run the Monthly function, variable must be a character

# Tidy R  pivot the data frame
VPivot = spread(VType, Type, Count)

# order the dates
VPivot = VPivot[order(VPivot$Date), ]

# Create the Time Series plot
TimeSeriesPlot2 = 
  plot_ly(VPivot, x = VPivot$Date, y = VPivot$ASSAULT, 
          type = "scatter", mode = "lines", name = "Assault", line = list(color = 'rgba(67,67,67,1)', width = 2)) %>%
  # add the remaining response variables variables to the plot
  add_trace(y = VPivot$BATTERY, name = "Battery", modes = "lines", 
            line = list(color = "dark blue"), width = 2 ) %>%
  add_trace(y = VPivot$HOMICIDE, name = "Homicide", modes = "lines", 
            line = list(color = "purple")) %>%
  add_trace(y = VPivot$ROBBERY, name = "Robbery", modes = "lines", 
            line = list(color = "blue")) %>%
  layout(title = "Violent Crime by Type 2010-2017",
         xaxis = list(title = "Date"), 
         yaxis = list(title = "Count")
  )

TimeSeriesPlot2
```

ANALYSIS OF SES DATA
```{r}
# Plotting time series plot for socioeconomic variables
socioeconla <- read.csv("SocioEconLA.csv")
socioeconla <- socioeconla[,c("Year","PopEst","HSEnr","MedIncome","Poverty","Unemp.1")]

## Time Series Plot for Socioeconomic Factors in Los Angeles

# Create the Time Series plot
tsplot3 = plot_ly(socioeconla, x = socioeconla$Year, y = socioeconla$PopEst, 
                 type = "scatter", mode = "lines", name = "Population Estimate", line = list(color = 'rgba(67,67,67,1)', width = 2)) %>%
  #Add the remaining response variables to the plot
  add_trace(y = socioeconla$HSEnr, name = "High School Enrollment", modes = "lines", 
            line = list(color = "dark blue"), width = 2 ) %>%
  add_trace(y = socioeconla$MedIncome, name = "Median Household Income ($)", modes = "lines", 
            line = list(color = "purple")) %>%
  add_trace(y = socioeconla$Poverty, name = "Population in Poverty", modes = "lines", 
            line = list(color = "blue")) %>%
  add_trace(y = socioeconla$Unemp.1, name = "Unemployed (16+)", modes = "lines", 
          line = list(color = "green")) %>%
    layout(title = "Los Angeles Socioeconomic Factors 2010-2017",
         xaxis = list(title = "Year"), 
         yaxis = list(title = "Population (or $)")
  )

tsplot3
```

DATA EXPLORATION
Preparing tract boundaries
```{r}
#MAPPING LA CRIME
#See STA 141A Lecture 11 slides
#Loading packages
library(ggmap)
library(rgdal)
library(scales)
library(dplyr)
library(Cairo)

#Preparing boundary shapefile

#Help from: https://stackoverflow.com/questions/29872109/binning-longitude-latitude-labeled-data-by-census-block-id (Code "Version 1")
tract <- readOGR(dsn = ".", layer = "census2010")
tract <- spTransform(x=tract, CRSobj=CRS("+proj=longlat +datum=WGS84"))

#Subsetting crimes by year
la_2010 = subset(la_violent, Year == "2010")
la_2011 = subset(la_violent, Year == "2011")
la_2012 = subset(la_violent, Year == "2012")
la_2013 = subset(la_violent, Year == "2013")
la_2014 = subset(la_violent, Year == "2014")
la_2015 = subset(la_violent, Year == "2015")
la_2016 = subset(la_violent, Year == "2016")
la_2017 = subset(la_violent, Year == "2017")

#Subsetting data
lonlat <- function(x) {
  y = data.frame(lat = x$lat, lon = x$lon)
  return(y)
}

lonlat.df10 <- lonlat(la_2010)
lonlat.df11 <- lonlat(la_2011)
lonlat.df12 <- lonlat(la_2012)
lonlat.df13 <- lonlat(la_2013)
lonlat.df14 <- lonlat(la_2014)
lonlat.df15 <- lonlat(la_2015)
lonlat.df16 <- lonlat(la_2016)
lonlat.df17 <- lonlat(la_2017)

#Converting data into a spatial points object
spdf <- function(x,y) {
  z = SpatialPointsDataFrame(coords=x[, c("lon", "lat")],
                                  data=y, proj4string=CRS("+proj=longlat +datum=WGS84"))
  return(z)
}

la_spdf10 <- spdf(lonlat.df10, la_2010)
la_spdf11 <- spdf(lonlat.df11, la_2011)
la_spdf12 <- spdf(lonlat.df12, la_2012)
la_spdf13 <- spdf(lonlat.df13, la_2013)
la_spdf14 <- spdf(lonlat.df14, la_2014)
la_spdf15 <- spdf(lonlat.df15, la_2015)
la_spdf16 <- spdf(lonlat.df16, la_2016)
la_spdf17 <- spdf(lonlat.df17, la_2017)

#Adding count column (each row is one crime incident)
spdf.list = list(la_spdf10,la_spdf11,la_spdf12,la_spdf13,la_spdf14,la_spdf15,la_spdf16,la_spdf17)

spdf <- function(x) {
  x@data$count <- 1
  return(x)
}

spdf.list <- lapply(spdf.list, spdf)

#Spatial overlay to identify census polygon in which each crime point falls
la_spdf_tract10 <- over(x=spdf.list[[1]], y=tract)
la_spdf_tract11 <- over(x=spdf.list[[2]], y=tract)
la_spdf_tract12 <- over(x=spdf.list[[3]], y=tract)
la_spdf_tract13 <- over(x=spdf.list[[4]], y=tract)
la_spdf_tract14 <- over(x=spdf.list[[5]], y=tract)
la_spdf_tract15 <- over(x=spdf.list[[6]], y=tract)
la_spdf_tract16 <- over(x=spdf.list[[7]], y=tract)
la_spdf_tract17 <- over(x=spdf.list[[8]], y=tract)

#Reassigning/delisting for ease of use
la_spdf10 = spdf.list[[1]]
la_spdf11 = spdf.list[[2]]
la_spdf12 = spdf.list[[3]]
la_spdf13 = spdf.list[[4]]
la_spdf14 = spdf.list[[5]]
la_spdf15 = spdf.list[[6]]
la_spdf16 = spdf.list[[7]]
la_spdf17 = spdf.list[[8]]

#Adding tract data to crime points
la_spdf10@data <- data.frame(la_spdf10@data, la_spdf_tract10)
la_spdf11@data <- data.frame(la_spdf11@data, la_spdf_tract11)
la_spdf12@data <- data.frame(la_spdf12@data, la_spdf_tract12)
la_spdf13@data <- data.frame(la_spdf13@data, la_spdf_tract13)
la_spdf14@data <- data.frame(la_spdf14@data, la_spdf_tract14)
la_spdf15@data <- data.frame(la_spdf15@data, la_spdf_tract15)
la_spdf16@data <- data.frame(la_spdf16@data, la_spdf_tract16)
la_spdf17@data <- data.frame(la_spdf17@data, la_spdf_tract17)

#Aggregate crimes by tract
agg = function(x) {
  y = aggregate(formula=count~GEOID10+Year, data=x@data, FUN=length)
  return(y)
}

ct10 <- agg(la_spdf10)
ct11 <- agg(la_spdf11)
ct12 <- agg(la_spdf12)
ct13 <- agg(la_spdf13)
ct14 <- agg(la_spdf14)
ct15 <- agg(la_spdf15)
ct16 <- agg(la_spdf16)
ct17 <- agg(la_spdf17)

#Merging all elements in ct.list
ct.list <- list(ct10,ct11,ct12,ct13,ct14,ct15,ct16,ct17)
ct = ct.list[[1]]
for (i in 2:length(ct.list)) {
  ct = rbind(ct, ct.list[[i]])
  i = i+1
}

#Help source: http://www.kevjohnson.org/making-maps-in-r/
#Joining crime_tract and tract on tract id's
tract.points <- fortify(tract, region = "GEOID10")

colnames(tract.points)[6] = "GEOID10"
plotdata10 = left_join(tract.points, ct10)
plotdata11 = left_join(tract.points, ct11)
plotdata12 = left_join(tract.points, ct12)
plotdata13 = left_join(tract.points, ct13)
plotdata14 = left_join(tract.points, ct14)
plotdata15 = left_join(tract.points, ct15)
plotdata16 = left_join(tract.points, ct16)
plotdata17 = left_join(tract.points, ct17)

#Plotting for 2010
p10 <- ggplot() +
    geom_polygon(data = plotdata10, aes(x = long, y = lat, group = group,
        fill = count), color = "black", size = 0.25)
p11 <- ggplot() +
    geom_polygon(data = plotdata11, aes(x = long, y = lat, group = group,
        fill = count), color = "black", size = 0.25)
p12 <- ggplot() +
    geom_polygon(data = plotdata12, aes(x = long, y = lat, group = group,
        fill = count), color = "black", size = 0.25)
p13 <- ggplot() +
    geom_polygon(data = plotdata13, aes(x = long, y = lat, group = group,
        fill = count), color = "black", size = 0.25)
p14 <- ggplot() +
    geom_polygon(data = plotdata14, aes(x = long, y = lat, group = group,
        fill = count), color = "black", size = 0.25)
p15 <- ggplot() +
    geom_polygon(data = plotdata15, aes(x = long, y = lat, group = group,
        fill = count), color = "black", size = 0.25)
p16 <- ggplot() +
    geom_polygon(data = plotdata16, aes(x = long, y = lat, group = group,
        fill = count), color = "black", size = 0.25)
p17 <- ggplot() +
    geom_polygon(data = plotdata17, aes(x = long, y = lat, group = group,
        fill = count), color = "black", size = 0.25)

#Plotting census tracts on map object
library(maptools)
library(RColorBrewer)

la = get_map("Los Angeles, CA")
la = ggmap(la)
colors <- brewer.pal(9, "BuGn")
la + geom_polygon(aes(x = long,
                   y = lat,
                   group = group),
               data = plotdata12,
               color = colors[9],
               fill = count,
               alpha = 0.5) +
  labs(x = "Longitude",
       y = "Latitude")
```

ANALYZING SOCIOECONOMIC FACTORS
```{r}
ses2 = read.csv("SESvars.csv")
lowcrime = subset(ses2, Area == "Devonshire (San Fernando Valley)"|
                  Area == "Hollenbeck (Central)"|
                  Area == "Harbor"|
                  Area == "Westside")
hicrime = subset(ses2, Area == "Southwest"|
                   Area == "South Bureau")  

ggplot(data=lowcrime, aes(x=Area, y=Val, group=Var, colour=Var)) +
    geom_line() 
ggplot(data=hicrime, aes(x=Area, y=Val, group=Var, colour=Var)) +
    geom_line() 

ses2sub <- subset(ses2, Var!="Pop")
lowcrime2 = subset(ses2sub, Area == "Devonshire (San Fernando Valley)"|
                  Area == "Hollenbeck (Central)"|
                  Area == "Harbor"|
                  Area == "Westside")
hicrime2 = subset(ses2sub, Area == "Southwest"|
                   Area == "South Bureau")
ggplot(data=lowcrime2, aes(x=Area, y=Val, group=Var, colour=Var)) +
    geom_line() 
ggplot(data=hicrime2, aes(x=Area, y=Val, group=Var, colour=Var)) +
    geom_line() 
```